INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 1, N'Mamma Mia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 2, N'Danish Red Dragons')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 3, N'Knitted Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 4, N'Los Tres Dragones')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 5, N'Mahjong Madrid')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 6, N'4 Orphans Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 7, N'Parrillada Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 8, N'Mahjong Valencia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 9, N'Mahjong Madrid 2')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 10, N'Mahjong Madrid 3')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 11, N'Magic Mahjong Self Pick!')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 12, N'Chulapong')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 13, N'Tapas & Mahjong')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 14, N'Italian Dragons')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 15, N'Swiss Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 1, N'Mahjong Madrid 2')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 2, N'Mahjong Madrid')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 3, N'Magic Mahjong')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 4, N'Los Mandrillos')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 5, N'Gazpachows')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 6, N'Cuatro orquídeas')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 7, N'Real de Francia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 8, N'Orange blossom')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 9, N'Serapias Insignis')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 10, N'Paso doble')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 11, N'Trombinoscope')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 12, N'4 orphans team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 13, N'Mahjong Valencia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 14, N'La verbena del pollo')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 15, N'Las Mojitas')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 16, N'Y arriba y arriba')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 17, N'Mahjonkies')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (2, 18, N'Knitted team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 1, N'BEST PLAYERS 2018 IN MADRID O YAYA')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 2, N'Win 100!')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 3, N'Mahjong Madrid')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 4, N'Three ladies and one man')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 5, N'F ''hu''d fighters')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 6, N'Mahjong Madrid 2')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 7, N'Chopsticks Masters')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 8, N'4 Orphans Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 9, N'Knitted Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 10, N'Mano Verde')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 11, N'#masti')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (3, 12, N'Los 13 Huertanicos')
