INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Afghanistan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Åland', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Albania', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Algeria', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'American Samoa', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Andorra', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Angola', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Anguilla', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Antigua and Barbuda', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Argentina', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Armenia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Aruba', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Australia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Austria', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Azerbaijan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bahamas', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bahrain', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bangladesh', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Barbados', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Belarus', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Belgium', N'BEL', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Belgium-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Belize', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Benin', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bermuda', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bhutan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bolivia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bonaire', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bosnia and Herzegovina', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Botswana', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Brazil', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'British Indian Ocean Territory', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'British Virgin Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Brunei', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Bulgaria', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Burkina Faso', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Burundi', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cambodia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cameroon', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Canada', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cape Verde', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cayman Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Central African Republic', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Chad', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Chile', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'China', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Christmas Island', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cocos [Keeling] Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Colombia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Comoros', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cook Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Costa Rica', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Croatia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cuba', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Curacao', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Cyprus', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Czechia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Democratic Republic of the Congo', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Denmark', N'DEN', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Denmark-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Djibouti', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Dominica', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Dominican Republic', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'East Timor', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Ecuador', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Egypt', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'El Salvador', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Equatorial Guinea', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Eritrea', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Estonia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Ethiopia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Falkland Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Faroe Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Fiji', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Finland', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'France', N'FRA', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/France-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'French Polynesia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Gabon', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Gambia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Georgia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Germany', N'GER', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Flag-of-Germany-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Ghana', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Gibraltar', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Great Britain', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Greece', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Greenland', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Grenada', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Guam', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Guatemala', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Guernsey', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Guinea', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Guinea-Bissau', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Haiti', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Honduras', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Hong Kong', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Hungary', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Iceland', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'India', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Indonesia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Iran', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Iraq', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Ireland', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Isle of Man', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Israel', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Italy', N'ITA', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Flag-of-Italy-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Ivory Coast', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Jamaica', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Japan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Jersey', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Jordan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Kazakhstan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Kenya', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Kiribati', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Kosovo', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Kuwait', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Kyrgyzstan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Laos', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Latvia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Lebanon', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Lesotho', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Liberia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Libya', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Liechtenstein', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Lithuania', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Luxembourg', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Macao', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Macedonia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Madagascar', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Malawi', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Malaysia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Maldives', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Mali', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Malta', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Marshall Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Martinique', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Mauritania', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Mauritius', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Mexico', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Micronesia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Moldova', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Monaco', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Mongolia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Montenegro', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Montserrat', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Morocco', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Mozambique', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Myanmar', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Namibia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Nauru', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Nepal', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Netherlands', N'NED', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Netherlands-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'New Zealand', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Nicaragua', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Niger', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Nigeria', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Niue', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'No Country', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Norfolk Island', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'North Korea', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Northern Mariana Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Norway', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Oman', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Pakistan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Palau', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Palestine', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Panama', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Papua New Guinea', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Paraguay', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Peru', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Philippines', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Pitcairn Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Poland', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Portugal', N'POR', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Portugal-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Puerto Rico', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Qatar', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Republic of the Congo', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Romania', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Russia', N'RUS', N'http://www.mahjongmadrid.com/wp-content/uploads/2017/03/rsz_russia.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Rwanda', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Saint Kitts and Nevis', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Saint Lucia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Saint Vincent and the Grenadines', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Samoa', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'San Marino', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'São Tomé and Príncipe', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Saudi Arabia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Senegal', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Serbia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Seychelles', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Sierra Leone', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Singapore', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Sint Maarten', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Slovakia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Slovenia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Solomon Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Somalia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'South Africa', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'South Korea', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'South Sudan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Spain', N'ESP', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Flag-of-Spain-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Sri Lanka', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Sudan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Suriname', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Swaziland', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Sweden', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Switzerland', N'SUI', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Switzerland-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Syria', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Taiwan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Tajikistan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Tanzania', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Thailand', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Togo', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Tokelau', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Tonga', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Trinidad and Tobago', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Tunisia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Turkey', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Turkmenistan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Turks and Caicos Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Tuvalu', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'U.S. Virgin Islands', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Uganda', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Ukraine', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'United Arab Emirates', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'United Kingdom', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'United States', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Uruguay', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Uzbekistan', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Vanuatu', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Vatican City', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Venezuela', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Vietnam', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Yemen', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Zambia', N'', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryShortName], [CountryHtmlImageUrl]) VALUES (N'Zimbabwe', N'', N'')
