INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 1, N'Annie Manzo', 1, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 2, N'Joel Ratsimandresy', 1, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 3, N'Bruno Manzo', 1, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 4, N'Christiane D''Angelo', 1, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 5, N'Camila Bonde', 2, N'Denmark', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 6, N'Shi Hua', 2, N'Denmark', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 7, N'Robert Bonde', 2, N'Denmark', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 8, N'Ting Fang', 2, N'Denmark', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 9, N'Anna Canova Putinier', 3, N'Switzerland', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 10, N'Thierry Claudel', 3, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 11, N'Laurent Claudel', 3, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 12, N'Timur Hahn', 3, N'Germany', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 13, N'Iván Maestre Ros', 4, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 14, N'Marta Soria Castellano', 4, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 15, N'David Martínez García', 4, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 16, N'Pilar Castellano Rivas', 4, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 17, N'Antonio Ayllón', 5, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 18, N'Héctor Escaso Gil', 5, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 19, N'Eduardo Amador Lorente', 5, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 20, N'Ernesto Vega de la Iglesia Soria', 5, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 21, N'Tina Christensen', 6, N'Denmark', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 22, N'Jacob Petersen', 6, N'Denmark', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 23, N'Annabel Di Domenico', 6, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 24, N'Reine-Marie Doris', 6, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 25, N'Caroline Arnaud', 7, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 26, N'Cédric Aguerre', 7, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 27, N'Simon Bunkeo Fongue', 7, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 28, N'Manuel Santos', 7, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 29, N'Rui Manuel Machado', 8, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 30, N'Edgar Rubio Rodilla', 8, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 31, N'José Moreno Merino', 8, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 32, N'Raúl Ríos Navarro', 8, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 33, N'Marco Antonio Olmos Domínguez', 9, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 34, N'Alejandro Serrano Vázquez', 9, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 35, N'Víctor González Fuentes', 9, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 36, N'Virginia Polonio Baeyens', 9, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 37, N'Frédéric Chassot', 10, N'Switzerland', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 38, N'Jorge Osuna Olalla', 10, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 39, N'Inma Cuevas Tortosa', 10, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 40, N'David Ciudad Gómez', 10, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 41, N'Ji Li Pfeiffer', 11, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 42, N'Matthieu Pfeiffer', 11, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 43, N'Bernard LAO', 11, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 44, N'Lionel Legaie', 11, N'France', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 45, N'Doming García García', 12, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 46, N'Katia Túnez Heredia', 12, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 47, N'Samuel Túnez Heredia', 12, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 48, N'Carmen Valbuena Medina', 12, N'Spain', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 49, N'Francesca Battaglini', 13, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 50, N'Serena Porrati', 13, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 51, N'Marco Montebelli', 13, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 52, N'Danilo Serio', 13, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 53, N'Miria Martelli', 14, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 54, N'Sebastian Ferrante', 14, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 55, N'Daniela Natali', 14, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 56, N'Claudia Folesani', 14, N'Italy', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 57, N'Gérard Hêche', 15, N'Switzerland', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 58, N'Tanja Mayr Delacrétaz', 15, N'Switzerland', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 59, N'Nathalie Jacquart', 15, N'Switzerland', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (1, 60, N'Luc Humbert', 15, N'Switzerland', N'')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 1, N'Virginia POLONIO BAEYENS', 1, N'Spain', N'10990056')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 2, N'José Manuel MORENO PESQUERA', 1, N'Spain', N'10990055')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 3, N'Abraham Antonio RIQUELME SÁNCHEZ', 1, N'Spain', N'10990063')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 4, N'Diana FUENTES CARREÑO', 1, N'Spain', N'10990012')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 5, N'Ernesto VEGA DE LA IGLESIA SORIA', 2, N'Spain', N'10990039')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 6, N'Antonio AYLLÓN', 2, N'Spain', N'10990027')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 7, N'Eduardo AMADOR LORENTE', 2, N'Spain', N'10990020')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 8, N'Héctor ESCASO GIL', 2, N'Spain', N'10990018')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 9, N'David CIUDAD GÓMEZ', 3, N'Spain', N'10990058')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 10, N'Ezequiel HERMOSIN', 3, N'Spain', N'10990061')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 11, N'Jorge OSUNA OLALLA', 3, N'Spain', N'10990059')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 12, N'Luis Eduardo RUBIO RODRIGUEZ', 3, N'Spain', N'10990057')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 13, N'Alberto ROSI', 4, N'Italy', N'7000114')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 14, N'Giuseppe IACOLINO', 4, N'Italy', N'7000115')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 15, N'Francesco MARTINI', 4, N'Italy', N'7000096')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 16, N'Marco FOSCHI', 4, N'Italy', N'7000070')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 17, N'Bruno MANZO', 5, N'France', N'4090025')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 18, N'Sandra BONDOIN', 5, N'France', N'4040047')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 19, N'Christiane D ANGELO', 5, N'France', N'4040036')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 20, N'Annie MANZO', 5, N'France', N'4090024')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 21, N'Michèle AUBRUN', 6, N'France', N'4090075')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 22, N'Patrick VENTURINI', 6, N'France', N'4090071')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 23, N'Daniel AUBRUN', 6, N'France', N'4990036')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 24, N'Thérèse ROBLIN', 6, N'France', N'4040110')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 25, N'Frédéric PETIT', 7, N'France', N'4040189')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 26, N'Vincent YOU-SEEN', 7, N'France', N'4990054')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 27, N'Florent DESCAMPS', 7, N'France', N'4120070')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 28, N'Jean Louis BARBET', 7, N'France', N'4030074')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 29, N'José MORENO MERINO', 8, N'Spain', N'10990007')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 30, N'Yvonne HEIDE, VAN DER', 8, N'Netherlands', N'8010052')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 31, N'Pauline LINDEN, VAN DER', 8, N'Netherlands', N'8010412')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 32, N'Ad LINDEN, VAN DER', 8, N'Netherlands', N'8010411')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 33, N'Cédric AGUERRE', 9, N'France', N'4090080')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 34, N'Denis LUGANNIKOV', 9, N'Russia', N'15990251')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 35, N'Caroline ARNAUD', 9, N'France', N'4090060')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 36, N'Simon Bounkéo FONGUE', 9, N'France', N'4090008')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 37, N'Marco MONTEBELLI', 10, N'Italy', N'7000018')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 38, N'Luca GAVELLI', 10, N'Italy', N'7000001')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 39, N'Daniela NATALI', 10, N'Italy', N'7000006')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 40, N'Serena PORRATI', 10, N'Italy', N'7000024')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 41, N'Cyrille RAK', 11, N'France', N'4090026')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 42, N'Francesca BATTAGLINI', 11, N'Italy', N'7000104')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 43, N'Danilo SERIO', 11, N'Italy', N'7000107')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 44, N'Agnès RAK', 11, N'France', N'4090016')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 45, N'Rui MANUEL MACHADO', 12, N'Portugal', N'12990002')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 46, N'Jos DERMOUT', 12, N'Belgium', N'2010039')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 47, N'Olivier ROY', 12, N'France', N'4210015')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 48, N'Anton KÖSTERS', 12, N'Netherlands', N'8010039')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 49, N'Edgar RUBIO RODILLA', 13, N'Spain', N'10990026')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 50, N'Raúl RÍOS NAVARRO', 13, N'Spain', N'10990043')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 51, N'Maria del Pilar CASTELLANO RIVAS', 13, N'Spain', N'10990025')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 52, N'Marcos SAN ANTONIO SERRANO', 13, N'Spain', N'10990051')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 53, N'Carmen VALBUENA MEDINA', 14, N'Spain', N'10990022')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 54, N'Maria del Mar TÚNEZ PÉREZ', 14, N'Spain', N'10990024')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 55, N'Katia TÚNEZ HEREDIA', 14, N'Spain', N'10990037')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 56, N'Ivan MAESTRE ROS', 14, N'Spain', N'10990016')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 57, N'Nathalie JACQUART', 15, N'Switzerland', N'16000009')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 58, N'Miria MARTELLI', 15, N'Italy', N'7000109')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 59, N'Anna CANOVA PUTINIER', 15, N'Switzerland', N'16000008')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 60, N'Tanja MAYR DELACRÉTAZ', 15, N'Switzerland', N'16000016')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 61, N'Nicoletta BASCHIROTTO', 16, N'Italy', N'7000150')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 62, N'Andrea VERPELLI', 16, N'Italy', N'7000008')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 63, N'Marco CIVAROLI', 16, N'Italy', N'7000163')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 64, N'Stefano RIJOFF', 16, N'Italy', N'7000009')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 65, N'Alejandro MARTÍNEZ FERNÁNDEZ', 17, N'Spain', N'10990028')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 66, N'Timur HAHN', 17, N'Germany', N'5100153')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 67, N'Emmanuelle HUGOT', 17, N'France', N'4290006')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 68, N'Elvira SANCHEZ FUENTES', 17, N'Spain', N'10990062')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 69, N'Christophe LEFEBVRE', 18, N'France', N'4040058')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 70, N'Leni JANSSEN', 18, N'Netherlands', N'8010036')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 71, N'Chris DE ROOCK', 18, N'Belgium', N'2010038')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (2, 72, N'Chris JANSSEN', 18, N'Netherlands', N'8010027')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 1, N'Anthony EA', 1, N'France', N'4040105')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 2, N'Anton KÖSTERS', 1, N'Netherlands', N'8010039')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 3, N'Erwan DE KERGOMMEAUX', 1, N'France', N'4290030')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 4, N'Loic DE KERGOMMEAUX', 1, N'France', N'4290031')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 5, N'Thérèse ROBLIN', 2, N'France', N'4040110')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 6, N'Shuyao HUANG', 2, N'France', N'4120060')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 7, N'Vincent YOU-SEEN', 2, N'France', N'4990054')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 8, N'Vincent TAN', 2, N'France', N'4040246')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 9, N'Maria del Pilar CASTELLANO RIVAS', 3, N'Spain', N'10990025')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 10, N'Héctor ESCASO GIL', 3, N'Spain', N'10990018')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 11, N'Antonio AYLLÓN', 3, N'Spain', N'10990027')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 12, N'Eduardo AMADOR LORENTE', 3, N'Spain', N'10990020')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 13, N'Domenico SANSEVIERI', 4, N'Italy', N'7000170')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 14, N'Laura ENFI', 4, N'Italy', N'7000078')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 15, N'Angela PLEBANI', 4, N'Italy', N'7000011')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 16, N'Daniela NATALI', 4, N'Italy', N'7000006')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 17, N'Stefano RIJOFF', 5, N'Italy', N'7000009')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 18, N'Marco MONTEBELLI', 5, N'Italy', N'7000018')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 19, N'Serena PORRATI', 5, N'Italy', N'7000024')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 20, N'Luca GAVELLI', 5, N'Italy', N'7000001')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 21, N'MARIA JOSE RODRIGUEZ SAN VICENTE', 6, N'Spain', N'10990071')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 22, N'Virginia POLONIO BAEYENS', 6, N'Spain', N'10990056')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 23, N'Víctor GONZÁLEZ FUENTE', 6, N'Spain', N'10990053')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 24, N'David CIUDAD GÓMEZ', 6, N'Spain', N'10990058')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 25, N'Ernesto VEGA DE LA IGLESIA SORIA', 7, N'Spain', N'10990039')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 26, N'Matthieu PFEIFFER', 7, N'France', N'4990062')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 27, N'Raúl RÍOS NAVARRO', 7, N'Spain', N'10990043')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 28, N'Ji Li PFEIFFER', 7, N'France', N'4040205')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 29, N'Rui MANUEL MACHADO', 8, N'Portugal', N'12990002')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 30, N'David SOLER RECIO', 8, N'Spain', N'10990070')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 31, N'Luis Eduardo RUBIO RODRIGUEZ', 8, N'Spain', N'10990057')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 32, N'José MORENO MERINO', 8, N'Spain', N'10990007')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 33, N'Augusto GHERARDI', 9, N'Italy', N'7000080')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 34, N'Christophe LEFEBVRE', 9, N'France', N'4040058')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 35, N'Miria MARTELLI', 9, N'Italy', N'7000109')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 36, N'Fabien GAUCHER', 9, N'France', N'4040238')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 37, N'Annie MANZO', 10, N'France', N'4090024')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 38, N'Joel RATSIMANDRESY', 10, N'France', N'4040057')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 39, N'Bruno MANZO', 10, N'France', N'4090025')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 40, N'Christiane D ANGELO', 10, N'France', N'4040036')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 41, N'Elena SAVINI', 11, N'Italy', N'7000021')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 42, N'Ombretta TASSINARI', 11, N'Italy', N'7000093')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 43, N'Giacomo FERRUZZI', 11, N'Italy', N'7000035')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 44, N'Alberto ROSI', 11, N'Italy', N'7000114')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 45, N'Samuel TÚNEZ HEREDIA', 12, N'Spain', N'10990017')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 46, N'Carmen VALBUENA MEDINA', 12, N'Spain', N'10990022')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 47, N'Katia TÚNEZ HEREDIA', 12, N'Spain', N'10990037')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName], [PlayerEmaNumber]) VALUES (3, 48, N'Edgar RUBIO RODILLA', 12, N'Spain', N'10990026')
