INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000001', N'SCHEICHENBAUER', N'Martin', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000009', N'TSCHINKEL', N'Norbert', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000013', N'DOPPELHOFER', N'Alexander', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000015', N'GLASER', N'Ernest', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000016', N'MYSLIVEC', N'Otto', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000022', N'ALDRIAN', N'Maria', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000024', N'STOLLWITZER', N'Margarete', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000025', N'JARITZ', N'Gerti', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000027', N'SALLMUTTER', N'Gabriele', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000030', N'RIHA', N'Eberhard', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000038', N'FRISCHENSCHLAGER', N'Elisabeth', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000039', N'POPRAT', N'Günter', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000045', N'GINTSBERGER', N'Günter', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000046', N'GINTSBERGER', N'Elvira', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000059', N'SALLMUTTER', N'Doris', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000060', N'DIVJAK', N'Felix', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000061', N'DIVJAK', N'Romana', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000069', N'RIEGLER', N'Helmut', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000071', N'MARESCH', N'Edeltraud', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000073', N'KANDORFER', N'Heinz', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000088', N'VOLLMANN - GAO', N'Qian', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000092', N'ALEXEJEW', N'Monika', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000093', N'FELSBERGER', N'Hermi', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000105', N'BERNKOPF', N'Johanna', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000108', N'TRINKL', N'Matthias', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000109', N'RIHA', N'Andreas', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'1000110', N'NEUWIRTH', N'Franz', N'Austria')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990007', N'MORENO MERINO', N'José', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990012', N'FUENTES CARREÑO', N'Diana', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990016', N'MAESTRE ROS', N'Ivan', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990017', N'TÚNEZ HEREDIA', N'Samuel', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990018', N'ESCASO GIL', N'Héctor', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990019', N'MARTÍNEZ GARCIA', N'David', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990020', N'AMADOR LORENTE', N'Eduardo', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990021', N'GARCÍA GARCÍA', N'Domingo', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990022', N'VALBUENA MEDINA', N'Carmen', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990024', N'TÚNEZ PÉREZ', N'Maria del Mar', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990025', N'CASTELLANO RIVAS', N'Maria del Pilar', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990026', N'RUBIO RODILLA', N'Edgar', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990027', N'AYLLÓN', N'Antonio', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990028', N'MARTÍNEZ FERNÁNDEZ', N'Alejandro', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990037', N'TÚNEZ HEREDIA', N'Katia', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990039', N'VEGA DE LA IGLESIA SORIA', N'Ernesto', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990043', N'RÍOS NAVARRO', N'Raúl', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990047', N'PASCUAL RAMÍREZ', N'Miguel', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990051', N'SAN ANTONIO SERRANO', N'Marcos', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990053', N'GONZÁLEZ FUENTE', N'Víctor', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990055', N'MORENO PESQUERA', N'José Manuel', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990056', N'POLONIO BAEYENS', N'Virginia', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990057', N'RUBIO RODRIGUEZ', N'Luis Eduardo', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990058', N'CIUDAD GÓMEZ', N'David', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990059', N'OSUNA OLALLA', N'Jorge', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990060', N'BALLESTER CARACENA', N'Mario', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990061', N'HERMOSIN', N'Ezequiel', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990062', N'SANCHEZ FUENTES', N'Elvira', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990063', N'RIQUELME SÁNCHEZ', N'Abraham Antonio', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990070', N'SOLER RECIO', N'David', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'10990071', N'RODRIGUEZ SAN VICENTE', N'MARIA JOSE', N'Spain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'11990005', N'FRASER', N'Ian', N'Great Britain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'11990016', N'DUCKWORTH', N'John', N'Great Britain')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'12990002', N'MANUEL MACHADO', N'Rui', N'Portugal')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990005', N'STEPANOV', N'Vladimir', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990008', N'DANILEVSKAYA', N'Alla', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990009', N'DULENKO', N'Galina', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990012', N'NOVIKOV', N'Vitaly', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990018', N'STEPANOVA', N'Anna', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990019', N'NETREBINA', N'Evgenia', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990021', N'CHICHIGINA', N'Natalya', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990023', N'ANOKHIN', N'Pavel', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990025', N'BABUSHKIN', N'Aleksandr', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990026', N'GOPTAREVA', N'Tatyana', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990027', N'LOGVINOV', N'Oleg', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990028', N'CHICHIGIN', N'Andrey', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990040', N'KVASHA', N'Ilya', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990042', N'MANDJIEV', N'Arslan', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990070', N'SHPILMAN', N'Anna', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990072', N'NESTER', N'Tatyana', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990075', N'BIRUKOV', N'Igor', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990078', N'TEREKHIN', N'Vladimir', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990086', N'VERDI', N'Anton', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990088', N'NECHAEV', N'Roman', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990091', N'RYZHANINA', N'Irina', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990092', N'DASHKOVA', N'Anna', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990093', N'USHAKOVA', N'Elena', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990095', N'DULENKO', N'Fedor', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990103', N'VASILIEV', N'Sergey', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990104', N'HLUDENTSOVA', N'Evgeniya', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990107', N'BOGATIKOV', N'Aleksander', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990108', N'CHERNYKH', N'Anastasiya', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990114', N'PETUHOV', N'Mikhail', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990117', N'BOGACHKOV', N'Dmitry', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990128', N'PANINA', N'Tamara', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990134', N'VERDI', N'Elena', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990135', N'ARZAMASCEV', N'Vladimir', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990174', N'KUDRYAVTSEVA', N'Anastasiya', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990175', N'MYSKIN', N'Filipp', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990176', N'GOLIKOVA', N'Natalia', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990177', N'ROMANETSKAYA', N'Olga', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990191', N'ZOLOTAREVA', N'Nadezhda', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990213', N'CHICHIGIN', N'Viacheslav', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990215', N'SHPILMAN', N'Aleksei', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990216', N'VERIK', N'Elena', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990233', N'MALAKHOV', N'Sergey', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990236', N'BYKOV', N'Dmitriy', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990251', N'LUGANNIKOV', N'Denis', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990265', N'SOLOVJEV', N'Anton', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990268', N'BELYALOVA', N'Maria', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990273', N'KIM', N'Evgeniy', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990291', N'ZINCHENKO', N'Vadim', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990315', N'MANIAKHIN', N'Petr', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990316', N'SAPOROVSKII', N'Andrei', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990317', N'SIMONOVA', N'Svetlana', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990318', N'KONSTANTINOVA', N'Ekaterina', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990324', N'IVANOV', N'Andrey', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990325', N'TOULINA', N'Ekaterina', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990327', N'LAVRENIUK', N'Irina', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990328', N'FILIUSHKINA', N'Veronika', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990332', N'KIRILLOVA', N'Anna', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990352', N'SVIDRITSKIY', N'Oleg', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990353', N'TURLINA', N'Elena', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'15990354', N'NEPOMNYASHCHIKH', N'Anastasiya', N'Russia')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000001', N'FELDER', N'Mei Hwa', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000002', N'LANG', N'Bo', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000005', N'HUMBERT', N'Luc', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000006', N'PETEREIT', N'Oliver', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000007', N'CHASSOT', N'Frédéric', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000008', N'CANOVA PUTINIER', N'Anna', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000009', N'JACQUART', N'Nathalie', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000010', N'GROUX', N'Marie-Hélène', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000011', N'HÊCHE', N'Gérard', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000016', N'MAYR DELACRÉTAZ', N'Tanja', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000020', N'DELAY', N'Patrice', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000021', N'HOFMANN', N'Marc-Antoine', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000025', N'DELACRETAZ', N'Sébastien', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000026', N'HERNANDEZ', N'Esther', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000027', N'HUNZIKER', N'Aurorita', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000030', N'ALONSO BLANCO', N'Marcos', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'16000031', N'LEE', N'Jun', N'Switzerland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'19000080', N'CHABELSKA', N'Katarzyna', N'Poland')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010001', N'MICHIELS', N'Yannick', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010014', N'VANDERBIST', N'Wenda', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010016', N'MOUS', N'Linda', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010021', N'VAN DAMME', N'Peter', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010022', N'MAES', N'Joke', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010024', N'MICHIELS', N'Irma', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010025', N'KOPMANIS', N'Rudy', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010028', N'DEWOLF', N'Marleen', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010031', N'MOUWEN', N'Emma', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010033', N'VERHEYDEN', N'Marieke', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010036', N'KAM', N'Benjamin', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010038', N'DE ROOCK', N'Chris', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010039', N'DERMOUT', N'Jos', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010040', N'RENSON', N'Tijs', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010041', N'PEVERNAGE', N'Hilde', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010042', N'KEMPER', N'Sophie', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010043', N'WECKHUYZEN', N'Tine', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010044', N'DERMOUT', N'Kristien', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010045', N'MORRENS', N'Arnaud', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010049', N'VERMEERSCH', N'Jonas', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010050', N'VAN HOOF', N'Anita', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010052', N'NAERT', N'Lies', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'2010053', N'GEUDENS', N'Linda', N'Belgium')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000003', N'CHRISTENSEN', N'Tina', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000005', N'STIG NIELSEN', N'Jeppe', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000022', N'LETH', N'Henrik', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000049', N'CHRISTIANSEN', N'Freddy', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000123', N'IVERSEN', N'Kim', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000126', N'THERKELSEN', N'Lars', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000140', N'CHEN KOLD', N'Shi Hua', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000142', N'ASKJæR-FRIIS', N'Mikkel', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000148', N'ROSTVED', N'Frank', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000149', N'BAHIANO STEENHOLM', N'Isabel', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000176', N'NØHR', N'Jesper', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000192', N'LAVALLEE', N'Sebastian', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000215', N'OLSEN', N'Ting Fang', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'3000313', N'PETERSEN', N'Jacob', N'Denmark')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010007', N'UGO', N'Jean Claude', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010011', N'CHAMPENOIS', N'Jean-Luc', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010015', N'DIFERNAND', N'Renéta', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010016', N'BONMALAIS', N'Eric', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010020', N'ROBERT', N'Frédéric', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010025', N'ENAULT', N'Gilbert', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010026', N'PAYET', N'Olivier', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010027', N'PAYET', N'Ghislaine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010028', N'TSONG CHIN CHUEN', N'Marcel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010039', N'LARINIER', N'Pascale', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010040', N'SAUNIE', N'Nicolas', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010052', N'BRONES', N'Félicia', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010054', N'EBLE', N'Philippe', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010055', N'EBLE', N'Catherine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010061', N'TAYLOR', N'Christine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010066', N'PAUSE', N'Annick', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4010076', N'CADI', N'Johanna', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030003', N'AUBERVAL', N'Jean Pascal', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030004', N'TAI LEUNG', N'Emmanuel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030005', N'AURE', N'David Gérard', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030006', N'AURE', N'Suzy', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030022', N'MORISSE', N'Jean Michel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030023', N'GRONDIN', N'Frédérique', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030028', N'ORREGIA', N'Marie-Josée', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030045', N'DORIS', N'Reine-Marie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030047', N'RODULFO', N'Jeannine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030048', N'RODULFO', N'Antoine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030062', N'JOURDAIN', N'David', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030067', N'LAW-THO', N'Marie-Claire', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030074', N'BARBET', N'Jean Louis', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030087', N'COSTEY', N'Jonathan', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030091', N'JANAC', N'Wilson Nathanaël', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030093', N'MC DONALD', N'James', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030100', N'MORISSE', N'Valérie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030103', N'RIVIERE', N'Mickaël', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030109', N'FONTAINE', N'Jean-Philippe', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4030124', N'BARRET', N'Cécile', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040010', N'BOIVIN', N'Olivier', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040017', N'SAHAL', N'Jérome', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040026', N'MESSI FOUDA', N'Benoit', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040034', N'LEGAIE', N'Lionel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040036', N'D ANGELO', N'Christiane', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040047', N'BONDOIN', N'Sandra', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040057', N'RATSIMANDRESY', N'Joel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040058', N'LEFEBVRE', N'Christophe', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040083', N'VIGNAUD', N'Hubert', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040105', N'EA', N'Anthony', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040110', N'ROBLIN', N'Thérèse', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040170', N'RAVEL', N'Judith', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040187', N'BARBET', N'Jérémie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040189', N'PETIT', N'Frédéric', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040205', N'PFEIFFER', N'Ji Li', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040212', N'GAO', N'François', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040217', N'LAO', N'Bernard', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040238', N'GAUCHER', N'Fabien', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4040246', N'TAN', N'Vincent', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4050007', N'VILLEPOU', N'Caroline', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4050022', N'BALAGOUROU', N'André', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060010', N'LAM WAN SHUM', N'Alfred', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060011', N'LAM WAN SHUM', N'Emilie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060014', N'METRO', N'Claudia', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060017', N'BENEGEAN', N'Monique', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060020', N'AH-LEUNG', N'Liliane', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060021', N'GUERIN', N'Michele', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060022', N'AH-PINE', N'Monique', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060023', N'CHANE YUM', N'Antoine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060025', N'THIM SIONG', N'Régine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060026', N'POTHIN', N'Gilette', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060027', N'LAFON', N'Jacqueline', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060031', N'GAUTRON', N'Fabienne', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060033', N'GONTHIER', N'Françoise', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060037', N'BAS', N'Micheline', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060042', N'SANGUY', N'Mauricette', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060049', N'PAUGAM', N'Colette', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060050', N'MAISTRY', N'Saaddyia', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060051', N'ROSTIN', N'Christine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060061', N'BAUD', N'Patrick', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4060067', N'PERROT', N'Brigitte', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080001', N'BOIDIN', N'Héléne', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080002', N'BALORIN', N'Pascal', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080004', N'ENAULT', N'Christian', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080005', N'LETOULLEC', N'René', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080007', N'GAUVIN', N'Annick', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080010', N'BOYER', N'Stéphanie Aline', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080018', N'GIGANT', N'Sylvie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080019', N'BARRATAULT', N'Maria', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4080021', N'DUBOZ', N'Simone', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090008', N'FONGUE', N'Simon Bounkéo', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090016', N'RAK', N'Agnès', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090024', N'MANZO', N'Annie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090025', N'MANZO', N'Bruno', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090026', N'RAK', N'Cyrille', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090035', N'DRAUX', N'Apolline', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090041', N'DELBOS', N'Josianne', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090045', N'BOUVET', N'Aymeric', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090059', N'MOREAU', N'Mélanie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090060', N'ARNAUD', N'Caroline', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090071', N'VENTURINI', N'Patrick', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090075', N'AUBRUN', N'Michèle', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090080', N'AGUERRE', N'Cédric', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090083', N'SVAY', N'Christina', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090088', N'FERRANTE', N'Sébastien', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090090', N'BONNEAU', N'Anne-Sophie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090091', N'LARRIGAUDIERE', N'Nathalie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090093', N'GUERIN', N'Guillaume', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4090098', N'ROYET', N'Anne', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4100018', N'GIRDARY', N'Marie Lucie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4120026', N'MOTHE', N'Norbert', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4120060', N'HUANG', N'Shuyao', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4120070', N'DESCAMPS', N'Florent', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130003', N'MATHERN', N'Claire', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130004', N'GUTSCHE', N'Sven-Hendrik', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130005', N'VALOGNES', N'Sylvie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130015', N'TOUSSAINT', N'Kevin', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130019', N'LEROY', N'Florine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130025', N'CLAUDEL', N'Laurent', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130026', N'LAPLAGNE', N'Fanette', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130027', N'HERDIER', N'Romain', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130032', N'XANTHOPOULOS', N'Catherine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130036', N'TOUSSAINT', N'Florence', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130055', N'XANTHOPOULOS', N'Tim', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130073', N'DES ROBERT', N'Dominique', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130092', N'SIMON', N'Alexandre', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4130106', N'DEMICHEL', N'Eva', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140001', N'GEFFRIAUD', N'Christophe', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140002', N'GEFFRIAUD', N'Evi', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140006', N'RICHOMME', N'Christophe', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140034', N'TCHERNYCHEV', N'Konstantin', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140040', N'HERMIER', N'Sarah', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140049', N'HOCHIN', N'Michèle', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140057', N'MIALIN', N'Monique', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4140059', N'CHARRIER', N'Françoise', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4160002', N'AZOUGAGH', N'Aziz', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4180001', N'HEDO', N'Joëlle', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4180005', N'CHEUNG-AH-SEUNG', N'Lucile', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4180009', N'TECHER', N'Daniel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4210013', N'BLOTTIN', N'Maeva', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4210015', N'ROY', N'Olivier', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4210018', N'TOUCAS', N'Elizabeth', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4210023', N'BOISSON', N'Véronique', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4240011', N'KIEFFER', N'Marie', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4240012', N'ZINNIGER', N'Christophe', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4280001', N'TACHE', N'Olivier', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4280004', N'DUBEDOUT', N'Astrid', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4280006', N'LE MORVAN', N'Éric', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4280011', N'CROCCO', N'Sébastien', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4290001', N'BERTHOMMIER', N'Sandra', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4290006', N'HUGOT', N'Emmanuelle', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4290008', N'PARRIAUD', N'Jean-François', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4290023', N'SANTOS', N'Manuel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4290030', N'DE KERGOMMEAUX', N'Erwan', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4290031', N'DE KERGOMMEAUX', N'Loic', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4290032', N'EREAU', N'Baptiste', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4390003', N'VAITILINGOM', N'Micheline', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4390007', N'HOARAU', N'Mathieu', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4390008', N'DE PALMAS', N'Joël', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4990015', N'CLAUDEL', N'Thierry', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4990024', N'DI DOMENICO', N'Annabel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4990025', N'DI DOMENICO', N'Corine', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4990036', N'AUBRUN', N'Daniel', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4990054', N'YOU-SEEN', N'Vincent', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'4990062', N'PFEIFFER', N'Matthieu', N'France')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100016', N'JENJAHN', N'Monika', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100017', N'GERDES', N'Erika', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100018', N'PÜNJER', N'Elke', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100020', N'MEIER', N'Marion', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100024', N'GERDES', N'Friedrich', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100033', N'DUHME', N'Stefanie', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100056', N'SCHÄFER', N'Heike', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100057', N'SCHÄFER', N'Anne', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100058', N'FISCHER', N'Dagmar', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100067', N'EICKSCHEN', N'Ulla', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100077', N'LUDWIG', N'Heidi', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100078', N'LUDWIG', N'Heinz', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100086', N'BOHLMANN', N'Fred', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100092', N'CAPITO', N'Cornelia', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100100', N'MANTEN', N'Sabine', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100101', N'DOMANN', N'Heiko', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100124', N'BEESE', N'Peter', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100127', N'MÜLLER', N'Robert', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100141', N'NOLTING', N'Bino', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100142', N'BRINKMEIER', N'Elke', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100143', N'CHEN', N'Wei', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100153', N'HAHN', N'Timur', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100164', N'GONG', N'Yixin', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5100165', N'SCHNIER', N'Jürgen', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5900002', N'KÖNIG', N'Nadine', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5900003', N'ZAHRADNIK', N'Michael', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5900008', N'BANSEMER', N'Silke', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'5900010', N'PEKAU', N'Uwe', N'Germany')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6010002', N'NYULASI', N'Zsolt', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6010008', N'BOGARNÈ NAGY', N'Magdolna', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6010011', N'HARGITAI', N'Ildikó', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6010021', N'TAKÁCS', N'Sándor', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6010022', N'TAKÁCSNÉ LOWINGER', N'Klára', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6010025', N'VÁRNAI', N'Eszter', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6010031', N'MÁTRAI', N'Jánosné', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6020003', N'HALÁSZ', N'Pál', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6020014', N'BERI', N'Márta Rózsa', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6020016', N'SPRECHER', N'Károly', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6020017', N'ELEK', N'David', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6020019', N'SZEPESVARI', N'Szilvia', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6020021', N'FÓRIZS', N'Ilona', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6990001', N'PALCZER-ASCHENBRENNER', N'Eti', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6990017', N'NEMETH', N'Attila', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'6990025', N'VLADAR', N'Ferenc', N'Hungary')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000001', N'GAVELLI', N'Luca', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000002', N'BAZZOCCHI', N'Marco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000005', N'BUSCARINI', N'Patrizia', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000006', N'NATALI', N'Daniela', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000007', N'MILANDRI', N'Marco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000008', N'VERPELLI', N'Andrea', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000009', N'RIJOFF', N'Stefano', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000011', N'PLEBANI', N'Angela', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000013', N'PROCOPIO', N'Stefania', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000014', N'BONALDO', N'Rosita', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000017', N'BOLLINO', N'Michele', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000018', N'MONTEBELLI', N'Marco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000020', N'PIZZI', N'Loretta', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000021', N'SAVINI', N'Elena', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000024', N'PORRATI', N'Serena', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000033', N'UGUCCIONI', N'Letizia', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000034', N'COMERCI', N'Michele', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000035', N'FERRUZZI', N'Giacomo', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000042', N'BASSI', N'Vittorio', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000048', N'PIANCASTELLI', N'Gianfranco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000052', N'LORENZI', N'Marco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000055', N'TRANCHINA', N'Massimiliano', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000062', N'BENINI', N'Paride', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000065', N'GORI', N'Stefania', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000070', N'FOSCHI', N'Marco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000071', N'ARGENTIERO', N'Giusi', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000072', N'GATTA', N'Bruna', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000075', N'FERRI', N'Fabrizio', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000078', N'ENFI', N'Laura', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000080', N'GHERARDI', N'Augusto', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000082', N'PEREGO', N'Roger', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000083', N'FOSCHI', N'Elisa', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000088', N'GARRIDO', N'Carmelita', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000089', N'CIOL', N'Maurizio', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000092', N'TARONI', N'Piero', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000093', N'TASSINARI', N'Ombretta', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000095', N'CALOSCI', N'Rossella', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000096', N'MARTINI', N'Francesco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000104', N'BATTAGLINI', N'Francesca', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000107', N'SERIO', N'Danilo', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000109', N'MARTELLI', N'Miria', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000111', N'PECE', N'Franca', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000114', N'ROSI', N'Alberto', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000115', N'IACOLINO', N'Giuseppe', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000119', N'PEDRINI', N'Enrica', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000124', N'PEDRINI', N'Roberta', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000127', N'MORIGI', N'Valentina', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000129', N'MARINO', N'Demetrio', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000130', N'VENTURI', N'Alberto', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000131', N'BAGNOLI', N'Maurizio', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000135', N'MOZNICH', N'Paolo', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000138', N'FOLESANI', N'Claudia', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000141', N'VALENTINO', N'Valentina', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000148', N'BONCRISTIANO', N'Luca', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000150', N'BASCHIROTTO', N'Nicoletta', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000151', N'FERUGLIO', N'Elisa', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000152', N'CERRA', N'Valentina', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000155', N'PALMISANO', N'Oscar', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000156', N'MAMONE', N'Laura', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000158', N'RENDA', N'Andrea', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000160', N'MASTRULLO', N'Davide', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000163', N'CIVAROLI', N'Marco', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000170', N'SANSEVIERI', N'Domenico', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'7000172', N'CRAGNOLIN', N'Luca', N'Italy')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010003', N'OORSCHOT, VAN', N'Gerda', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010017', N'SCHEFFLER', N'Chris', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010021', N'HEEMSKERK', N'Désirée', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010022', N'ONNINK', N'Janco', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010023', N'HEEMSKERK', N'Yvonne', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010025', N'CROEZE', N'Marianne', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010026', N'CROEZE', N'Jaap', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010027', N'JANSSEN', N'Chris', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010028', N'BROERS', N'Eveline', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010035', N'HEIJN', N'Berry', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010036', N'JANSSEN', N'Leni', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010039', N'KÖSTERS', N'Anton', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010047', N'BROEDER', N'Ingrid', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010049', N'VEGT, VAN DER', N'Gert', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010052', N'HEIDE, VAN DER', N'Yvonne', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010054', N'SCHOLTE', N'Piet', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010083', N'SOHANA', N'Ma Prem', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010101', N'BALKUM, VAN', N'Eric', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010109', N'MEIJER', N'Jeroen', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010113', N'TEUNISSEN', N'Eugenie', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010120', N'SATRIASAPUTRA', N'Dewi', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010121', N'MEIJER - KAL', N'Wil', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010122', N'BIE, VAN DER', N'Tonny', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010123', N'BIE, VAN DER', N'Gerard', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010126', N'WONG-CHUNG', N'Rudy', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010128', N'KAL', N'Harry', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010137', N'JONG, DE', N'Zeger', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010140', N'ELFERINK', N'Petra', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010158', N'WESTDIJK', N'Diana', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010162', N'MOREL', N'Hanneke', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010166', N'HOOGLAND', N'Ans', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010168', N'GRINSVEN, VAN', N'Dimphy', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010171', N'CLAESSEN', N'Bert', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010173', N'KEYL', N'Anneke', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010187', N'BRINK, VAN DEN', N'Cees', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010196', N'DONK', N'Grea', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010206', N'ELFERINK', N'Leo', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010219', N'GROOT, DE', N'Aty', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010271', N'MEIJER', N'Trees', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010295', N'PUTTEN, VAN DER', N'Ria', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010305', N'VAN WIJK', N'Janine', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010328', N'WARBOUT', N'Jan', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010344', N'PILGRAM', N'Jack lien', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010351', N'KUIJPERS', N'John', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010376', N'MARSIDI', N'Ieneke', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010411', N'LINDEN, VAN DER', N'Ad', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010412', N'LINDEN, VAN DER', N'Pauline', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010415', N'ARINGANENG', N'Nino', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010427', N'PASTERKAMP', N'Martha', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010430', N'OORSOUW, VAN', N'Anja', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010445', N'VOS', N'Barry', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010470', N'BAZUIN', N'Cisca', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010486', N'BAKKER', N'Anneke', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010495', N'LIENDEN VAN', N'Menno', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010505', N'MEULENDIJK', N'Sonja', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010510', N'WEBER', N'Mieke', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010518', N'BOEKSTAAF', N'Dennis', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010526', N'SOMMERS', N'Olav', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010538', N'HAGMAN', N'Annie', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010545', N'CORNE', N'Neil', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010557', N'VAN THIEL', N'Martin', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010564', N'KITSLAAR', N'Annet', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010568', N'NOLTEN', N'Jannie', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010569', N'SCHAADERS', N'Leny', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010580', N'BAKKER', N'Foppe', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010593', N'BOOGAART', N'Anja', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010594', N'OORSOUW, VAN', N'Mattheu', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010598', N'VAN DE NIEUWENDIJK', N'Oscar', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010599', N'VAN DE NIEUWENDIJK', N'Marjan', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010609', N'HOOGLAND', N'Jose', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010613', N'LIPS', N'Marjoleine', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010621', N'SCHOLTEN', N'Rik', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010633', N'JONG, DE', N'Joke', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010650', N'DE VRIES', N'Jakko', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010656', N'DROST', N'Vera', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010665', N'BOSKAMP', N'Liesbeth', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010667', N'NIEUWENDIJK', N'Twan', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010687', N'HEYLIGER', N'Jessica', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010689', N'LAMMERS', N'Ronald', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010698', N'VAN BALKUM', N'Luuk', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010699', N'MALLEE', N'Annemiek', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010701', N'KOSTER', N'Ineke', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010706', N'CRAAIKAMP', N'Anna', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010727', N'OUDSHOOM', N'Jacqueline', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010730', N'DEIJ - VAN RIJSWIJK', N'Menno', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010731', N'VAN WIJNGAARDEN', N'Sandra', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010732', N'VAN MOURIK', N'Herma', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'8010733', N'BOL', N'Pieter', N'Netherlands')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990008', N'HENRIËT', N'Moa', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990009', N'ÖSTMAN', N'Emelie', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990039', N'NORÉN', N'Marie', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990044', N'RANEFALL', N'Petter', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990045', N'RIDELL', N'Annika', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990047', N'GERMEYS', N'Jasper', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990088', N'FAHLSTRÖM', N'Emma', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990095', N'HJORT', N'Mikael', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990099', N'AVENEL', N'Christophe', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990104', N'NORÉN', N'Caroline', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990106', N'LANDOLSI', N'Sara', N'Sweden')
INSERT INTO [dbo].[DBEmaPlayers] ([EmaPlayerEmaNumber], [EmaPlayerLastName], [EmaPlayerName], [EmaPlayerCountryName]) VALUES (N'9990107', N'GABOARDI', N'Felipe', N'Sweden')
