INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 1, N'Mahjong Madrid 2')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 2, N'Mahjong Madrid')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 3, N'Magic Mahjong')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 4, N'Los Mandrillos')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 5, N'Gazpachows')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 6, N'Cuatro orquídeas')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 7, N'Real de Francia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 8, N'Orange blossom')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 9, N'Serapias Insignis')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 10, N'Paso doble')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 11, N'Trombinoscope')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 12, N'4 orphans team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 13, N'Mahjong Valencia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 14, N'La verbena del pollo')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 15, N'Las Mojitas')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 16, N'Y arriba y arriba')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 17, N'Mahjonkies')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 18, N'Knitted team')
