INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 1, N'Annie Manzo', 1, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 2, N'Joel Ratsimandresy', 1, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 3, N'Bruno Manzo', 1, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 4, N'Christiane D''Angelo', 1, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 5, N'Camila Bonde', 2, N'Denmark')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 6, N'Shi Hua', 2, N'Denmark')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 7, N'Robert Bonde', 2, N'Denmark')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 8, N'Ting Fang', 2, N'Denmark')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 9, N'Anna Canova Putinier', 3, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 10, N'Thierry Claudel', 3, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 11, N'Laurent Claudel', 3, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 12, N'Timur Hahn', 3, N'Germany')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 13, N'Iván Maestre Ros', 4, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 14, N'Marta Soria Castellano', 4, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 15, N'David Martínez García', 4, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 16, N'Pilar Castellano Rivas', 4, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 17, N'Antonio Ayllón', 5, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 18, N'Héctor Escaso Gil', 5, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 19, N'Eduardo Amador Lorente', 5, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 20, N'Ernesto Vega de la Iglesia Soria', 5, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 21, N'Tina Christensen', 6, N'Denmark')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 22, N'Jacob Petersen', 6, N'Denmark')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 23, N'Annabel Di Domenico', 6, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 24, N'Reine-Marie Doris', 6, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 25, N'Caroline Arnaud', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 26, N'Cédric Aguerre', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 27, N'Simon Bunkeo Fongue', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 28, N'Manuel Santos', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 29, N'Rui Manuel Machado', 8, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 30, N'Edgar Rubio Rodilla', 8, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 31, N'José Moreno Merino', 8, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 32, N'Raúl Ríos Navarro', 8, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 33, N'Marco Antonio Olmos Domínguez', 9, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 34, N'Alejandro Serrano Vázquez', 9, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 35, N'Víctor González Fuentes', 9, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 36, N'Virginia Polonio Baeyens', 9, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 37, N'Frédéric Chassot', 10, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 38, N'Jorge Osuna Olalla', 10, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 39, N'Inma Cuevas Tortosa', 10, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 40, N'David Ciudad Gómez', 10, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 41, N'Ji Li Pfeiffer', 11, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 42, N'Matthieu Pfeiffer', 11, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 43, N'Bernard LAO', 11, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 44, N'Lionel Legaie', 11, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 45, N'Doming García García', 12, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 46, N'Katia Túnez Heredia', 12, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 47, N'Samuel Túnez Heredia', 12, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 48, N'Carmen Valbuena Medina', 12, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 49, N'Francesca Battaglini', 13, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 50, N'Serena Porrati', 13, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 51, N'Marco Montebelli', 13, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 52, N'Danilo Serio', 13, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 53, N'Miria Martelli', 14, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 54, N'Sebastian Ferrante', 14, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 55, N'Daniela Natali', 14, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 56, N'Claudia Folesani', 14, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 57, N'Gérard Hêche', 15, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 58, N'Tanja Mayr Delacrétaz', 15, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 59, N'Nathalie Jacquart', 15, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 60, N'Luc Humbert', 15, N'Switzerland')
