INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 1, N'Mamma Mia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 2, N'Danish Red Dragons')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 3, N'Knitted Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 4, N'Los Tres Dragones')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 5, N'Mahjong Madrid')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 6, N'4 Orphans Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 7, N'Parrillada Team')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 8, N'Mahjong Valencia')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 9, N'Mahjong Madrid 2')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 10, N'Mahjong Madrid 3')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 11, N'Magic Mahjong Self Pick!')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 12, N'Chulapong')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 13, N'Tapas & Mahjong')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 14, N'Italian Dragons')
INSERT INTO [dbo].[DBTeams] ([TeamTournamentId], [TeamId], [TeamName]) VALUES (1, 15, N'Swiss Team')
