using System.Drawing;

namespace MahjongTournamentSuite.Resources.flags
{
    class CountryFlags
    {
        public static Image GetFlagImage(string playerCountryName)
        {
            switch(playerCountryName)
            {
                case "Andorra":
                    return Properties.Resources.Andorra;
                case "United_Arab_Emirates":
                    return Properties.Resources.United_Arab_Emirates;
                case "Afghanistan":
                    return Properties.Resources.Afghanistan;
                case "Antigua_and_Barbuda":
                    return Properties.Resources.Antigua_and_Barbuda;
                case "Anguilla":
                    return Properties.Resources.Anguilla;
                case "Albania":
                    return Properties.Resources.Albania;
                case "Armenia":
                    return Properties.Resources.Armenia;
                case "Angola":
                    return Properties.Resources.Angola;
                case "Argentina":
                    return Properties.Resources.Argentina;
                case "American_Samoa":
                    return Properties.Resources.American_Samoa;
                case "Austria":
                    return Properties.Resources.Austria;
                case "Australia":
                    return Properties.Resources.Australia;
                case "Aruba":
                    return Properties.Resources.Aruba;
                case "Åland":
                    return Properties.Resources.Åland;
                case "Azerbaijan":
                    return Properties.Resources.Azerbaijan;
                case "Bosnia_and_Herzegovina":
                    return Properties.Resources.Bosnia_and_Herzegovina;
                case "Barbados":
                    return Properties.Resources.Barbados;
                case "Bangladesh":
                    return Properties.Resources.Bangladesh;
                case "Belgium":
                    return Properties.Resources.Belgium;
                case "Burkina_Faso":
                    return Properties.Resources.Burkina_Faso;
                case "Bulgaria":
                    return Properties.Resources.Bulgaria;
                case "Bahrain":
                    return Properties.Resources.Bahrain;
                case "Burundi":
                    return Properties.Resources.Burundi;
                case "Benin":
                    return Properties.Resources.Benin;
                case "Bermuda":
                    return Properties.Resources.Bermuda;
                case "Brunei":
                    return Properties.Resources.Brunei;
                case "Bolivia":
                    return Properties.Resources.Bolivia;
                case "Bonaire":
                    return Properties.Resources.Bonaire;
                case "Brazil":
                    return Properties.Resources.Brazil;
                case "Bahamas":
                    return Properties.Resources.Bahamas;
                case "Bhutan":
                    return Properties.Resources.Bhutan;
                case "Botswana":
                    return Properties.Resources.Botswana;
                case "Belarus":
                    return Properties.Resources.Belarus;
                case "Belize":
                    return Properties.Resources.Belize;
                case "Canada":
                    return Properties.Resources.Canada;
                case "Cocos_[Keeling]_Islands":
                    return Properties.Resources.Cocos__Keeling__Islands;
                case "Democratic_Republic_of_the_Congo":
                    return Properties.Resources.Democratic_Republic_of_the_Congo;
                case "Central_African_Republic":
                    return Properties.Resources.Central_African_Republic;
                case "Republic_of_the_Congo":
                    return Properties.Resources.Republic_of_the_Congo;
                case "Switzerland":
                    return Properties.Resources.Switzerland;
                case "Ivory_Coast":
                    return Properties.Resources.Ivory_Coast;
                case "Cook_Islands":
                    return Properties.Resources.Cook_Islands;
                case "Chile":
                    return Properties.Resources.Chile;
                case "Cameroon":
                    return Properties.Resources.Cameroon;
                case "China":
                    return Properties.Resources.China;
                case "Colombia":
                    return Properties.Resources.Colombia;
                case "Costa_Rica":
                    return Properties.Resources.Costa_Rica;
                case "Cuba":
                    return Properties.Resources.Cuba;
                case "Cape_Verde":
                    return Properties.Resources.Cape_Verde;
                case "Curacao":
                    return Properties.Resources.Curacao;
                case "Christmas_Island":
                    return Properties.Resources.Christmas_Island;
                case "Cyprus":
                    return Properties.Resources.Cyprus;
                case "Czechia":
                    return Properties.Resources.Czechia;
                case "Germany":
                    return Properties.Resources.Germany;
                case "Djibouti":
                    return Properties.Resources.Djibouti;
                case "Denmark":
                    return Properties.Resources.Denmark;
                case "Dominica":
                    return Properties.Resources.Dominica;
                case "Dominican_Republic":
                    return Properties.Resources.Dominican_Republic;
                case "Algeria":
                    return Properties.Resources.Algeria;
                case "Ecuador":
                    return Properties.Resources.Ecuador;
                case "Estonia":
                    return Properties.Resources.Estonia;
                case "Egypt":
                    return Properties.Resources.Egypt;
                case "Eritrea":
                    return Properties.Resources.Eritrea;
                case "Spain":
                    return Properties.Resources.Spain;
                case "Ethiopia":
                    return Properties.Resources.Ethiopia;
                case "Finland":
                    return Properties.Resources.Finland;
                case "Fiji":
                    return Properties.Resources.Fiji;
                case "Falkland_Islands":
                    return Properties.Resources.Falkland_Islands;
                case "Micronesia":
                    return Properties.Resources.Micronesia;
                case "Faroe_Islands":
                    return Properties.Resources.Faroe_Islands;
                case "France":
                    return Properties.Resources.France;
                case "Gabon":
                    return Properties.Resources.Gabon;
                case "United_Kingdom":
                    return Properties.Resources.United_Kingdom;
                case "Grenada":
                    return Properties.Resources.Grenada;
                case "Georgia":
                    return Properties.Resources.Georgia;
                case "Guernsey":
                    return Properties.Resources.Guernsey;
                case "Ghana":
                    return Properties.Resources.Ghana;
                case "Gibraltar":
                    return Properties.Resources.Gibraltar;
                case "Greenland":
                    return Properties.Resources.Greenland;
                case "Gambia":
                    return Properties.Resources.Gambia;
                case "Guinea":
                    return Properties.Resources.Guinea;
                case "Equatorial_Guinea":
                    return Properties.Resources.Equatorial_Guinea;
                case "Greece":
                    return Properties.Resources.Greece;
                case "Guatemala":
                    return Properties.Resources.Guatemala;
                case "Guam":
                    return Properties.Resources.Guam;
                case "Guinea-Bissau":
                    return Properties.Resources.Guinea_Bissau;
                case "Hong_Kong":
                    return Properties.Resources.Hong_Kong;
                case "Honduras":
                    return Properties.Resources.Honduras;
                case "Croatia":
                    return Properties.Resources.Croatia;
                case "Haiti":
                    return Properties.Resources.Haiti;
                case "Hungary":
                    return Properties.Resources.Hungary;
                case "Indonesia":
                    return Properties.Resources.Indonesia;
                case "Ireland":
                    return Properties.Resources.Ireland;
                case "Israel":
                    return Properties.Resources.Israel;
                case "Isle_of_Man":
                    return Properties.Resources.Isle_of_Man;
                case "India":
                    return Properties.Resources.India;
                case "British_Indian_Ocean_Territory":
                    return Properties.Resources.British_Indian_Ocean_Territory;
                case "Iraq":
                    return Properties.Resources.Iraq;
                case "Iran":
                    return Properties.Resources.Iran;
                case "Iceland":
                    return Properties.Resources.Iceland;
                case "Italy":
                    return Properties.Resources.Italy;
                case "Jersey":
                    return Properties.Resources.Jersey;
                case "Jamaica":
                    return Properties.Resources.Jamaica;
                case "Jordan":
                    return Properties.Resources.Jordan;
                case "Japan":
                    return Properties.Resources.Japan;
                case "Kenya":
                    return Properties.Resources.Kenya;
                case "Kyrgyzstan":
                    return Properties.Resources.Kyrgyzstan;
                case "Cambodia":
                    return Properties.Resources.Cambodia;
                case "Kiribati":
                    return Properties.Resources.Kiribati;
                case "Comoros":
                    return Properties.Resources.Comoros;
                case "Saint_Kitts_and_Nevis":
                    return Properties.Resources.Saint_Kitts_and_Nevis;
                case "North_Korea":
                    return Properties.Resources.North_Korea;
                case "South_Korea":
                    return Properties.Resources.South_Korea;
                case "Kuwait":
                    return Properties.Resources.Kuwait;
                case "Cayman_Islands":
                    return Properties.Resources.Cayman_Islands;
                case "Kazakhstan":
                    return Properties.Resources.Kazakhstan;
                case "Laos":
                    return Properties.Resources.Laos;
                case "Lebanon":
                    return Properties.Resources.Lebanon;
                case "Saint_Lucia":
                    return Properties.Resources.Saint_Lucia;
                case "Liechtenstein":
                    return Properties.Resources.Liechtenstein;
                case "Sri_Lanka":
                    return Properties.Resources.Sri_Lanka;
                case "Liberia":
                    return Properties.Resources.Liberia;
                case "Lesotho":
                    return Properties.Resources.Lesotho;
                case "Lithuania":
                    return Properties.Resources.Lithuania;
                case "Luxembourg":
                    return Properties.Resources.Luxembourg;
                case "Latvia":
                    return Properties.Resources.Latvia;
                case "Libya":
                    return Properties.Resources.Libya;
                case "Morocco":
                    return Properties.Resources.Morocco;
                case "Monaco":
                    return Properties.Resources.Monaco;
                case "Moldova":
                    return Properties.Resources.Moldova;
                case "Montenegro":
                    return Properties.Resources.Montenegro;
                case "Madagascar":
                    return Properties.Resources.Madagascar;
                case "Marshall_Islands":
                    return Properties.Resources.Marshall_Islands;
                case "Macedonia":
                    return Properties.Resources.Macedonia;
                case "Mali":
                    return Properties.Resources.Mali;
                case "Myanmar":
                    return Properties.Resources.Myanmar;
                case "Mongolia":
                    return Properties.Resources.Mongolia;
                case "Macao":
                    return Properties.Resources.Macao;
                case "Northern_Mariana_Islands":
                    return Properties.Resources.Northern_Mariana_Islands;
                case "Martinique":
                    return Properties.Resources.Martinique;
                case "Mauritania":
                    return Properties.Resources.Mauritania;
                case "Montserrat":
                    return Properties.Resources.Montserrat;
                case "Malta":
                    return Properties.Resources.Malta;
                case "Mauritius":
                    return Properties.Resources.Mauritius;
                case "Maldives":
                    return Properties.Resources.Maldives;
                case "Malawi":
                    return Properties.Resources.Malawi;
                case "Mexico":
                    return Properties.Resources.Mexico;
                case "Malaysia":
                    return Properties.Resources.Malaysia;
                case "Mozambique":
                    return Properties.Resources.Mozambique;
                case "Namibia":
                    return Properties.Resources.Namibia;
                case "Niger":
                    return Properties.Resources.Niger;
                case "Norfolk_Island":
                    return Properties.Resources.Norfolk_Island;
                case "Nigeria":
                    return Properties.Resources.Nigeria;
                case "Nicaragua":
                    return Properties.Resources.Nicaragua;
                case "Netherlands":
                    return Properties.Resources.Netherlands;
                case "Norway":
                    return Properties.Resources.Norway;
                case "Nepal":
                    return Properties.Resources.Nepal;
                case "Nauru":
                    return Properties.Resources.Nauru;
                case "Niue":
                    return Properties.Resources.Niue;
                case "New_Zealand":
                    return Properties.Resources.New_Zealand;
                case "Oman":
                    return Properties.Resources.Oman;
                case "Panama":
                    return Properties.Resources.Panama;
                case "Peru":
                    return Properties.Resources.Peru;
                case "French_Polynesia":
                    return Properties.Resources.French_Polynesia;
                case "Papua_New_Guinea":
                    return Properties.Resources.Papua_New_Guinea;
                case "Philippines":
                    return Properties.Resources.Philippines;
                case "Pakistan":
                    return Properties.Resources.Pakistan;
                case "Poland":
                    return Properties.Resources.Poland;
                case "Pitcairn_Islands":
                    return Properties.Resources.Pitcairn_Islands;
                case "Puerto_Rico":
                    return Properties.Resources.Puerto_Rico;
                case "Palestine":
                    return Properties.Resources.Palestine;
                case "Portugal":
                    return Properties.Resources.Portugal;
                case "Palau":
                    return Properties.Resources.Palau;
                case "Paraguay":
                    return Properties.Resources.Paraguay;
                case "Qatar":
                    return Properties.Resources.Qatar;
                case "Romania":
                    return Properties.Resources.Romania;
                case "Serbia":
                    return Properties.Resources.Serbia;
                case "Russia":
                    return Properties.Resources.Russia;
                case "Rwanda":
                    return Properties.Resources.Rwanda;
                case "Saudi_Arabia":
                    return Properties.Resources.Saudi_Arabia;
                case "Solomon_Islands":
                    return Properties.Resources.Solomon_Islands;
                case "Seychelles":
                    return Properties.Resources.Seychelles;
                case "Sudan":
                    return Properties.Resources.Sudan;
                case "Sweden":
                    return Properties.Resources.Sweden;
                case "Singapore":
                    return Properties.Resources.Singapore;
                case "Slovenia":
                    return Properties.Resources.Slovenia;
                case "Slovakia":
                    return Properties.Resources.Slovakia;
                case "Sierra_Leone":
                    return Properties.Resources.Sierra_Leone;
                case "San_Marino":
                    return Properties.Resources.San_Marino;
                case "Senegal":
                    return Properties.Resources.Senegal;
                case "Somalia":
                    return Properties.Resources.Somalia;
                case "Suriname":
                    return Properties.Resources.Suriname;
                case "South_Sudan":
                    return Properties.Resources.South_Sudan;
                case "São_Tomé_and_Príncipe":
                    return Properties.Resources.São_Tomé_and_Príncipe;
                case "El_Salvador":
                    return Properties.Resources.El_Salvador;
                case "Sint_Maarten":
                    return Properties.Resources.Sint_Maarten;
                case "Syria":
                    return Properties.Resources.Syria;
                case "Swaziland":
                    return Properties.Resources.Swaziland;
                case "Turks_and_Caicos_Islands":
                    return Properties.Resources.Turks_and_Caicos_Islands;
                case "Chad":
                    return Properties.Resources.Chad;
                case "Togo":
                    return Properties.Resources.Togo;
                case "Thailand":
                    return Properties.Resources.Thailand;
                case "Tajikistan":
                    return Properties.Resources.Tajikistan;
                case "Tokelau":
                    return Properties.Resources.Tokelau;
                case "East_Timor":
                    return Properties.Resources.East_Timor;
                case "Turkmenistan":
                    return Properties.Resources.Turkmenistan;
                case "Tunisia":
                    return Properties.Resources.Tunisia;
                case "Tonga":
                    return Properties.Resources.Tonga;
                case "Turkey":
                    return Properties.Resources.Turkey;
                case "Trinidad_and_Tobago":
                    return Properties.Resources.Trinidad_and_Tobago;
                case "Tuvalu":
                    return Properties.Resources.Tuvalu;
                case "Taiwan":
                    return Properties.Resources.Taiwan;
                case "Tanzania":
                    return Properties.Resources.Tanzania;
                case "Ukraine":
                    return Properties.Resources.Ukraine;
                case "Uganda":
                    return Properties.Resources.Uganda;
                case "United_States":
                    return Properties.Resources.United_States;
                case "Uruguay":
                    return Properties.Resources.Uruguay;
                case "Uzbekistan":
                    return Properties.Resources.Uzbekistan;
                case "Vatican_City":
                    return Properties.Resources.Vatican_City;
                case "Saint_Vincent_and_the_Grenadines":
                    return Properties.Resources.Saint_Vincent_and_the_Grenadines;
                case "Venezuela":
                    return Properties.Resources.Venezuela;
                case "British_Virgin_Islands":
                    return Properties.Resources.British_Virgin_Islands;
                case "U.S._Virgin_Islands":
                    return Properties.Resources.U_S__Virgin_Islands;
                case "Vietnam":
                    return Properties.Resources.Vietnam;
                case "Vanuatu":
                    return Properties.Resources.Vanuatu;
                case "Samoa":
                    return Properties.Resources.Samoa;
                case "Kosovo":
                    return Properties.Resources.Kosovo;
                case "Yemen":
                    return Properties.Resources.Yemen;
                case "South_Africa":
                    return Properties.Resources.South_Africa;
                case "Zambia":
                    return Properties.Resources.Zambia;
                case "Zimbabwe":
                    return Properties.Resources.Zimbabwe;
                default:
                    return null;
            }
        }
    }
}
