INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 1, N'Virginia Polonio Baeyens', 1, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 2, N'Jose Manuel Moreno Pesquera', 1, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 3, N'Abraham Riquelme Sánchez', 1, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 4, N'Diana Fuentes Carreño', 1, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 5, N'Ernesto Vega  de la Iglesia', 2, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 6, N'Antonio Ayllón', 2, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 7, N'Eduardo Amador lorente', 2, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 8, N'Héctor Escaso Gil', 2, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 9, N'David Ciudad Gómez', 3, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 10, N'Ezequiel Hermosín', 3, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 11, N'Jorge Osuna Olalla', 3, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 12, N'Luis E. Rubio Rodríguez', 3, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 13, N'Alberto Rosi', 4, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 14, N'Giuseppe Iacolino', 4, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 15, N'Francesco Martini', 4, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 16, N'Marco Foschi', 4, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 17, N'Bruno Manzo', 5, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 18, N'Sandra Bondoin', 5, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 19, N'Christiane D''Angelo', 5, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 20, N'Annie Manzo', 5, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 21, N'Michelle Aubrun', 6, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 22, N'Patrick Venturini', 6, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 23, N'Daniel Aubrun', 6, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 24, N'Thérèse Roblin', 6, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 25, N'Frédèric Petit', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 26, N'Vincent You-Seen', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 27, N'Florent Descamps', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 28, N'Jean Louis Barbet', 7, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 29, N'José Moreno Merino', 8, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 30, N'Yvonne van der Heide', 8, N'Netherlands')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 31, N'Pauline van der Linden', 8, N'Netherlands')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 32, N'Ad van der Linden', 8, N'Netherlands')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 33, N'Cédric Aguerre', 9, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 34, N'Denis Lugannikov', 9, N'Russia')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 35, N'Caroline Arnaud', 9, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 36, N'Simon Fongue', 9, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 37, N'Marco Montebelli', 10, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 38, N'Luca Gavelli', 10, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 39, N'Daniela Natali', 10, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 40, N'Serena Porrati', 10, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 41, N'Cyrille Rak', 11, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 42, N'Francesca Battaglini', 11, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 43, N'Danilo Serio', 11, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 44, N'Agnes Rak', 11, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 45, N'Rui Machado', 12, N'Portugal')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 46, N'Jos Dermout', 12, N'Belgium')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 47, N'Olivier Roy', 12, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 48, N'Anton Kösters', 12, N'Netherlands')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 49, N'Edgar Rubio Rodilla', 13, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 50, N'Raúl Ríos Navarro', 13, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 51, N'Pilar Castellano Rivas', 13, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 52, N'Marcos San Antonio Serrano', 13, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 53, N'Carmen Valbuena Medina', 14, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 54, N'Mar Túnez Pérez', 14, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 55, N'Katia Túnez Heredia', 14, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 56, N'Iván Maestre Ros', 14, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 57, N'Nathalie Jacquart', 15, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 58, N'Miria Martelli', 15, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 59, N'Anna Canova Putinier', 15, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 60, N'Tanja Mayr Delacretaz', 15, N'Switzerland')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 61, N'Nicoletta Baschirotto', 16, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 62, N'Andrea Verpelli', 16, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 63, N'Marco Civaroli', 16, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 64, N'Stefano Rijoff', 16, N'Italy')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 65, N'Alejandro Martínez Fernández', 17, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 66, N'Timur Hahn', 17, N'Germany')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 67, N'Emmanuelle Hugot', 17, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 68, N'Elvira Sánchez Fuentes', 17, N'Spain')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 69, N'Cristophe Lefebvre', 18, N'France')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 70, N'Leni Janssen', 18, N'Netherlands')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 71, N'Chris De Roock', 18, N'Belgium')
INSERT INTO [dbo].[DBPlayers] ([PlayerTournamentId], [PlayerId], [PlayerName], [PlayerTeamId], [PlayerCountryName]) VALUES (1, 72, N'Chris Janssen', 18, N'Netherlands')
