INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Afghanistan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Åland', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Albania', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Algeria', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'American Samoa', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Andorra', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Angola', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Anguilla', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Antigua and Barbuda', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Argentina', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Armenia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Aruba', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Australia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Austria', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Azerbaijan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bahamas', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bahrain', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bangladesh', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Barbados', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Belarus', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Belgium', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Belgium-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Belize', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Benin', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bermuda', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bhutan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bolivia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bonaire', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bosnia and Herzegovina', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Botswana', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Brazil', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'British Indian Ocean Territory', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'British Virgin Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Brunei', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Bulgaria', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Burkina Faso', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Burundi', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cambodia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cameroon', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Canada', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cape Verde', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cayman Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Central African Republic', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Chad', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Chile', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'China', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Christmas Island', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cocos [Keeling] Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Colombia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Comoros', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cook Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Costa Rica', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Croatia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cuba', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Curacao', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Cyprus', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Czechia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Democratic Republic of the Congo', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Denmark', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Denmark-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Djibouti', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Dominica', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Dominican Republic', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'East Timor', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Ecuador', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Egypt', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'El Salvador', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Equatorial Guinea', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Eritrea', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Estonia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Ethiopia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Falkland Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Faroe Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Fiji', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Finland', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'France', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/France-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'French Polynesia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Gabon', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Gambia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Georgia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Germany', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Flag-of-Germany-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Ghana', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Gibraltar', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Greece', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Greenland', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Grenada', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Guam', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Guatemala', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Guernsey', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Guinea', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Guinea-Bissau', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Haiti', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Honduras', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Hong Kong', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Hungary', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Iceland', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'India', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Indonesia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Iran', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Iraq', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Ireland', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Isle of Man', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Israel', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Italy', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Flag-of-Italy-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Ivory Coast', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Jamaica', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Japan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Jersey', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Jordan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Kazakhstan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Kenya', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Kiribati', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Kosovo', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Kuwait', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Kyrgyzstan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Laos', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Latvia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Lebanon', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Lesotho', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Liberia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Libya', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Liechtenstein', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Lithuania', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Luxembourg', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Macao', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Macedonia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Madagascar', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Malawi', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Malaysia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Maldives', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Mali', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Malta', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Marshall Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Martinique', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Mauritania', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Mauritius', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Mexico', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Micronesia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Moldova', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Monaco', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Mongolia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Montenegro', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Montserrat', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Morocco', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Mozambique', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Myanmar', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Namibia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Nauru', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Nepal', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Netherlands', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Netherlands-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'New Zealand', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Nicaragua', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Niger', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Nigeria', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Niue', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'No Country', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Norfolk Island', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'North Korea', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Northern Mariana Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Norway', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Oman', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Pakistan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Palau', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Palestine', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Panama', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Papua New Guinea', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Paraguay', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Peru', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Philippines', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Pitcairn Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Poland', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Portugal', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Portugal-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Puerto Rico', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Qatar', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Republic of the Congo', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Romania', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Russia', N'http://www.mahjongmadrid.com/wp-content/uploads/2017/03/rsz_russia.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Rwanda', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Saint Kitts and Nevis', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Saint Lucia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Saint Vincent and the Grenadines', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Samoa', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'San Marino', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'São Tomé and Príncipe', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Saudi Arabia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Senegal', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Serbia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Seychelles', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Sierra Leone', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Singapore', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Sint Maarten', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Slovakia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Slovenia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Solomon Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Somalia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'South Africa', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'South Korea', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'South Sudan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Spain', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Flag-of-Spain-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Sri Lanka', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Sudan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Suriname', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Swaziland', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Sweden', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Switzerland', N'http://www.mahjongmadrid.com/wp-content/uploads/2016/05/Switzerland-32.png')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Syria', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Taiwan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Tajikistan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Tanzania', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Thailand', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Togo', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Tokelau', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Tonga', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Trinidad and Tobago', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Tunisia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Turkey', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Turkmenistan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Turks and Caicos Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Tuvalu', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'U.S. Virgin Islands', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Uganda', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Ukraine', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'United Arab Emirates', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'United Kingdom', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'United States', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Uruguay', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Uzbekistan', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Vanuatu', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Vatican City', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Venezuela', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Vietnam', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Yemen', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Zambia', N'')
INSERT INTO [dbo].[DBCountries] ([CountryName], [CountryHtmlImageUrl]) VALUES (N'Zimbabwe', N'')
